'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const engine = require('../js/tax-engine-2025.js');

// All fixtures assume a single Canadian-resident employee under 65, no spouse or
// dependants, no credits/deductions beyond those modeled, and one province for
// residence and employment. Official formula links and full assumptions are in
// docs/2025-tax-model.md. Expected amounts below are literal hand-calculated
// fixtures, not values generated by the implementation under test.
//
// Returned annual money amounts are rounded to cents. A two-cent tolerance
// allows for progressive-form arithmetic performed with unrounded cents versus
// line-by-line form rounding. Contribution boundary helpers are tested directly
// with a tighter floating-point tolerance.
function close(actual, expected, tolerance = 0.02) {
  assert.ok(Math.abs(actual - expected) <= tolerance, `expected ${actual} to be within ${tolerance} of ${expected}`);
}

function warningCodes(result) {
  return result.warnings.map((warning) => warning.code);
}

test('zero income produces zero tax, contributions, and cash', () => {
  const result = engine.calculateEstimate({ provinceCode: 'ON', employmentIncome: 0, monthlyExpenses: 0 });
  assert.equal(result.grossCashIncome, 0);
  assert.equal(result.taxableIncome, 0);
  assert.equal(result.incomeTaxPlusPayrollContributions, 0);
  assert.equal(result.spendableCashAfterRrsp, 0);
  assert.equal(result.monthlySurplus, 0);
});

test('income below the basic personal amount has no income tax', () => {
  // $10,000 employment: CPP = ($10,000-$3,500)*(4.95%+1%) = $386.75;
  // EI = $10,000*1.64% = $164. Federal and Ontario gross tax are fully
  // offset by the supported non-refundable credits.
  const result = engine.calculateEstimate({ provinceCode: 'ON', employmentIncome: 10000 });
  assert.equal(result.federalIncomeTax, 0);
  assert.equal(result.provincialIncomeTax, 0);
  close(result.cppOrQpp, 386.75);
  close(result.employeeEi, 164);
  close(result.spendableCashAfterRrsp, 9449.25);
});

test('Ontario employee at $50,000 with no RRSP matches the hand fixture', () => {
  // CPP base $2,301.75 + enhanced $465 = $2,766.75; EI $820;
  // taxable income $49,535. Federal tax $4,177.92125.
  // Ontario: gross $2,501.5175 - NRTC $801.371875 - LIFT $23.25
  // + $600 health premium = $2,276.895625.
  const result = engine.calculateEstimate({ provinceCode: 'ON', employmentIncome: 50000 });
  close(result.taxableIncome, 49535);
  close(result.federalIncomeTax, 4177.92);
  close(result.provincialIncomeTax, 2276.90);
  close(result.cppOrQpp, 2766.75);
  close(result.employeeEi, 820);
  close(result.incomeTaxPlusPayrollContributions, 10041.57);
  close(result.spendableCashAfterRrsp, 39958.43);
});

test('Ontario employee at $80,000 with no RRSP matches the hand fixture', () => {
  // CPP $3,356.10 + $678 + ($80,000-$71,300)*4% = $4,382.10;
  // EI $1,077.48; enhanced deduction $1,026; taxable income $78,974.
  // Federal $9,552.3009; Ontario $4,190.17571 + $750 OHP.
  const result = engine.calculateEstimate({ provinceCode: 'ON', employmentIncome: 80000 });
  close(result.taxableIncome, 78974);
  close(result.federalIncomeTax, 9552.30);
  close(result.provincialIncomeTax, 4940.18);
  close(result.cppOrQpp, 4382.10);
  close(result.employeeEi, 1077.48);
  close(result.incomeTaxPlusPayrollContributions, 19952.06);
  close(result.spendableCashAfterRrsp, 60047.94);
});

test('Ontario $80,000 with a deductible $10,000 RRSP separates tax saving and cash funding', () => {
  // Taxable income $68,974. Federal $7,502.3009. Ontario gross-after-credit
  // $3,275.17571 + $600 OHP = $3,875.17571. The independently calculated
  // income-tax reduction is $3,115; the $10,000 contribution is still a cash use.
  const result = engine.calculateEstimate({
    provinceCode: 'ON', employmentIncome: 80000,
    rrspContribution: 10000, availableRrspDeductionLimit: 10000
  });
  close(result.rrspDeduction, 10000);
  close(result.federalIncomeTax, 7502.30);
  close(result.provincialIncomeTax, 3875.18);
  close(result.rrspIncomeTaxReduction, 3115);
  close(result.afterTaxCashBeforeRrsp, 63162.94);
  close(result.spendableCashAfterRrsp, 53162.94);
  assert.ok(result.spendableCashAfterRrsp < 60047.94);
});

test('high-income Ontario fixture triggers surtax and the maximum health premium', () => {
  // At $250,000 employment income, taxable income is $248,926 after the
  // $1,074 enhanced CPP deduction. Ontario base tax after NRTCs is
  // $23,896.63881. Surtax = 20%*($23,896.63881-$5,710)
  // +36%*($23,896.63881-$7,307) = $9,609.5977336; OHP = $900.
  const result = engine.calculateEstimate({ provinceCode: 'ON', employmentIncome: 250000 });
  close(result.taxableIncome, 248926);
  close(result.federalIncomeTax, 54120.45);
  close(result.ontarioSurtax, 9609.60);
  close(result.ontarioHealthPremium, 900);
  close(result.provincialIncomeTax, 34406.24);
});

test('CPP second earnings band applies above the $71,300 first ceiling', () => {
  // At $75,000: first-ceiling CPP is $4,034.10 and CPP2 is
  // ($75,000-$71,300)*4% = $148, for $4,182.10 total employee CPP.
  const payroll = engine.calculatePayrollContributions(75000, 'ON');
  close(payroll.cppOrQpp, 4182.10, 0.0001);
  close(payroll.secondEnhancedPension, 148, 0.0001);
});

test('Quebec $80,000 employee fixture includes QPP, lower EI, QPIP, worker deduction, and abatement', () => {
  // QPP = $3,661.20 base + $678 enhanced + $348 QPP2 = $4,687.20;
  // EI $860.67; QPIP $395.20. Federal basic tax $9,482.19485 less
  // 16.5% abatement = $7,917.6327. Quebec taxable income is
  // $80,000-$1,026 enhanced QPP-$1,420 worker deduction = $77,554;
  // provincial tax = [$53,255*14% + $24,299*19%] - $18,571*14% = $9,472.57.
  const result = engine.calculateEstimate({ provinceCode: 'QC', employmentIncome: 80000 });
  close(result.cppOrQpp, 4687.20);
  close(result.employeeEi, 860.67);
  close(result.employeeQpip, 395.20);
  close(result.provincialTaxableIncome, 77554);
  close(result.federalQuebecAbatement, 1564.56);
  close(result.federalIncomeTax, 7917.63);
  close(result.provincialIncomeTax, 9472.57);
  close(result.incomeTaxPlusPayrollContributions, 23333.27);
  assert.ok(warningCodes(result).includes('QUEBEC_LIMITED_SUPPORT'));
});

test('British Columbia $80,000 fixture uses the BC form rates and credits', () => {
  // BC gross tax = $49,279*5.06% + $29,695*7.7% = $4,780.0324.
  // BC NRTC = ($12,932+$3,356.10+$1,077.48)*5.06% = $878.698348.
  const result = engine.calculateEstimate({ provinceCode: 'BC', employmentIncome: 80000 });
  close(result.federalIncomeTax, 9552.30);
  close(result.provincialIncomeTax, 3901.33);
  close(result.incomeTaxPlusPayrollContributions, 18913.21);
  close(result.spendableCashAfterRrsp, 61086.79);
});

test('British Columbia low-income fixture applies the BC tax reduction after non-refundable credits', () => {
  // $30,000 employment gives a $265 enhanced CPP deduction, so taxable/net
  // income is $29,735. BC428: gross tax = $29,735 × 5.06% = $1,504.591;
  // NRTCs = ($12,932 BPA + $1,311.75 base CPP + $492 EI) × 5.06%
  // = $745.62895. The BC reduction is $562 - ($29,735 - $25,020)
  // × 3.56% = $394.146. Tax = $1,504.591 - $745.62895 - $394.146
  // = $364.81605.
  const result = engine.calculateEstimate({ provinceCode: 'BC', employmentIncome: 30000 });
  close(result.provincialDetails.taxReduction, 394.146);
  close(result.provincialIncomeTax, 364.82);
});

test('Manitoba low-income fixture treats the Family Tax Benefit as a credit-base amount', () => {
  // $20,000 employment: base CPP = ($20,000-$3,500) × 4.95% = $816.75;
  // enhanced CPP deduction = $165; EI = $328; taxable/net income = $19,835.
  // MB428-A: Family Tax Benefit = $2,065 - ($19,835 × 9%) = $279.85.
  // MB428: gross tax = $19,835 × 10.8% = $2,142.18. Credit base is
  // $15,780 BPA + $816.75 base CPP + $328 EI + $279.85 Family Tax Benefit
  // = $17,204.60; NRTCs = $17,204.60 × 10.8% = $1,858.0968.
  // Manitoba tax = $2,142.18 - $1,858.0968 = $284.0832.
  const result = engine.calculateEstimate({ provinceCode: 'MB', employmentIncome: 20000 });
  close(result.provincialDetails.familyTaxBenefit, 279.85);
  close(result.provincialDetails.nonRefundableCredits, 1858.0968);
  close(result.provincialDetails.taxReduction, 0);
  close(result.provincialIncomeTax, 284.08);
});

test('Alberta $80,000 fixture applies the finalized 8% bracket and evaluates its supplemental credit', () => {
  const result = engine.calculateEstimate({ provinceCode: 'AB', employmentIncome: 80000 });
  // AB428: 60,000 × 8% + 18,974 × 10% = 6,697.40 gross tax.
  // Credits: (22,323 BPA + 3,356.10 base CPP + 1,077.48 EI) × 8% = 2,140.53.
  close(result.provincialIncomeTax, 4556.87);
  assert.equal(result.provincialDetails.supplementalTaxCredit, 0);
  close(result.spendableCashAfterRrsp, 60431.25);
});

test('two jobs are combined for one annual CPP exemption and ceilings', () => {
  // Combined $70,000 employment: pensionable earnings $66,500;
  // CPP base $3,291.75 + enhanced $665 = $3,956.75; EI is capped
  // at $1,077.48. Taxable income is $69,335.
  const result = engine.calculateEstimate({
    provinceCode: 'ON',
    jobs: [{ mode: 'annual', annualSalary: 40000 }, { mode: 'annual', annualSalary: 30000 }]
  });
  close(result.employmentIncome, 70000);
  close(result.cppOrQpp, 3956.75);
  close(result.employeeEi, 1077.48);
  close(result.taxableIncome, 69335);
  close(result.incomeTaxPlusPayrollContributions, 16531.32);
});

test('working weeks plus paid vacation over 52 produces a warning without percentage double counting', () => {
  const job = engine.calculateEmploymentIncome({
    mode: 'hourly', hourlyRate: 20, hoursPerWeek: 40,
    workingWeeks: 50, paidVacationWeeks: 3, vacationPayPercent: 0
  });
  assert.equal(job.income, 42400);
  assert.ok(warningCodes(job).includes('WEEKS_OVER_52'));
});

test('job warnings retain the zero-based job index for accessible field targeting', () => {
  const result = engine.calculateEstimate({
    provinceCode: 'ON',
    jobs: [
      { mode: 'hourly', hourlyRate: 20, hoursPerWeek: 40, workingWeeks: 50, paidVacationWeeks: 2 },
      { mode: 'hourly', hourlyRate: 20, hoursPerWeek: 10, workingWeeks: 51, paidVacationWeeks: 2 }
    ]
  });
  const warning = result.warnings.find((item) => item.code === 'WEEKS_OVER_52');
  assert.equal(warning.jobIndex, 1);
});

test('conflicting vacation methods use paid weeks once and report the conflict', () => {
  const job = engine.calculateEmploymentIncome({
    mode: 'hourly', hourlyRate: 20, hoursPerWeek: 40,
    workingWeeks: 50, paidVacationWeeks: 3, vacationPayPercent: 4
  });
  assert.equal(job.income, 42400);
  assert.ok(warningCodes(job).includes('VACATION_METHOD_CONFLICT'));
});

test('expenses above spendable cash produce negative monthly and weekly deficits', () => {
  // $9,449.25 annual spendable cash / 12 = $787.4375. With $1,000
  // monthly expenses, deficit is $212.5625 monthly and $49.0529 weekly.
  const result = engine.calculateEstimate({ provinceCode: 'ON', employmentIncome: 10000, monthlyExpenses: 1000 });
  close(result.monthlySpendableCash, 787.44);
  close(result.monthlySurplus, -212.56);
  close(result.weeklySurplus, -49.05);
  assert.ok(result.monthlySurplus < 0);
});

test('RRSP contribution above entered limit limits only the deduction, not the cash outflow', () => {
  // $6,000 is deducted; the independently calculated tax reduction is
  // $1,779. The full $10,000 contribution reduces spendable cash.
  const result = engine.calculateEstimate({
    provinceCode: 'ON', employmentIncome: 80000,
    rrspContribution: 10000, availableRrspDeductionLimit: 6000
  });
  close(result.rrspDeduction, 6000);
  close(result.rrspIncomeTaxReduction, 1779);
  close(result.spendableCashAfterRrsp, 51826.94);
  assert.ok(warningCodes(result).includes('RRSP_LIMIT_EXCEEDED'));
});

test('RRSP contribution without a confirmed limit gets no deduction but still reduces cash', () => {
  const result = engine.calculateEstimate({ provinceCode: 'ON', employmentIncome: 80000, rrspContribution: 10000 });
  close(result.rrspDeduction, 0);
  close(result.spendableCashAfterRrsp, 50047.94);
  assert.ok(warningCodes(result).includes('RRSP_LIMIT_REQUIRED'));
});

test('increasing deductible RRSP contributions never increases spendable cash', () => {
  let prior = Infinity;
  [0, 1000, 5000, 10000, 20000, 30000].forEach((contribution) => {
    const result = engine.calculateEstimate({
      provinceCode: 'ON', employmentIncome: 80000,
      rrspContribution: contribution, availableRrspDeductionLimit: 50000
    });
    assert.ok(result.spendableCashAfterRrsp <= prior, `${contribution} contribution unexpectedly increased spendable cash`);
    prior = result.spendableCashAfterRrsp;
  });
});

test('federal first-bracket boundary is continuous immediately below, at, and above', () => {
  close(engine.taxByBrackets(57374, engine.FEDERAL_BRACKETS), 8319.23, 0.0001);
  close(engine.taxByBrackets(57375, engine.FEDERAL_BRACKETS), 8319.375, 0.0001);
  close(engine.taxByBrackets(57376, engine.FEDERAL_BRACKETS), 8319.58, 0.0001);
});

test('CPP first and second ceiling boundaries are capped correctly', () => {
  close(engine.calculatePayrollContributions(71299, 'ON').cppOrQpp, 4034.0405, 0.0001);
  close(engine.calculatePayrollContributions(71300, 'ON').cppOrQpp, 4034.10, 0.0001);
  close(engine.calculatePayrollContributions(71301, 'ON').cppOrQpp, 4034.14, 0.0001);
  close(engine.calculatePayrollContributions(81199, 'ON').cppOrQpp, 4430.06, 0.0001);
  close(engine.calculatePayrollContributions(81200, 'ON').cppOrQpp, 4430.10, 0.0001);
  close(engine.calculatePayrollContributions(81201, 'ON').cppOrQpp, 4430.10, 0.0001);
});

test('EI maximum-insurable-earnings boundary is capped correctly', () => {
  close(engine.calculatePayrollContributions(65699, 'ON').ei, 1077.4636, 0.0001);
  close(engine.calculatePayrollContributions(65700, 'ON').ei, 1077.48, 0.0001);
  close(engine.calculatePayrollContributions(65701, 'ON').ei, 1077.48, 0.0001);
});

test('EI premiums are refunded at the $2,000 annual-insurable-earnings boundary', () => {
  close(engine.calculatePayrollContributions(1999, 'ON').ei, 0, 0.0001);
  close(engine.calculatePayrollContributions(2000, 'ON').ei, 0, 0.0001);
  close(engine.calculatePayrollContributions(2000.01, 'ON').ei, 32.800164, 0.0001);
});

test('income-dependent federal and Manitoba BPAs respect their phase-out boundaries', () => {
  close(engine.federalBasicPersonalAmount(177882), 16129, 0.0001);
  close(engine.federalBasicPersonalAmount(253414), 14538, 0.0001);
  close(engine.manitobaBasicPersonalAmount(200000), 15780, 0.0001);
  close(engine.manitobaBasicPersonalAmount(300000), 7890, 0.0001);
  close(engine.manitobaBasicPersonalAmount(400000), 0, 0.0001);
});

test('all 13 province and territory codes return finite base-case results', () => {
  const codes = ['BC', 'AB', 'SK', 'MB', 'ON', 'QC', 'NB', 'NS', 'PE', 'NL', 'YT', 'NT', 'NU'];
  codes.forEach((provinceCode) => {
    const result = engine.calculateEstimate({ provinceCode, employmentIncome: 60000 });
    assert.equal(result.taxYear, 2025);
    assert.ok(Number.isFinite(result.federalIncomeTax));
    assert.ok(Number.isFinite(result.provincialIncomeTax));
    assert.ok(Number.isFinite(result.spendableCashAfterRrsp));
    assert.equal(result.support, provinceCode === 'QC' ? 'limited' : 'supported');
  });
});
